// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	inputs "microservice/internals/a/adapters/inputs"

	mock "github.com/stretchr/testify/mock"

	tables "microservice/databases/postgresql/tables"
)

// IRepository is an autogenerated mock type for the IRepository type
type IRepository struct {
	mock.Mock
}

type IRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IRepository) EXPECT() *IRepository_Expecter {
	return &IRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: input
func (_m *IRepository) Add(input inputs.AddInput) error {
	ret := _m.Called(input)

	var r0 error
	if rf, ok := ret.Get(0).(func(inputs.AddInput) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type IRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - input inputs.AddInput
func (_e *IRepository_Expecter) Add(input interface{}) *IRepository_Add_Call {
	return &IRepository_Add_Call{Call: _e.mock.On("Add", input)}
}

func (_c *IRepository_Add_Call) Run(run func(input inputs.AddInput)) *IRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(inputs.AddInput))
	})
	return _c
}

func (_c *IRepository_Add_Call) Return(_a0 error) *IRepository_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IRepository_Add_Call) RunAndReturn(run func(inputs.AddInput) error) *IRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: input
func (_m *IRepository) Delete(input inputs.DeleteInput) error {
	ret := _m.Called(input)

	var r0 error
	if rf, ok := ret.Get(0).(func(inputs.DeleteInput) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type IRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - input inputs.DeleteInput
func (_e *IRepository_Expecter) Delete(input interface{}) *IRepository_Delete_Call {
	return &IRepository_Delete_Call{Call: _e.mock.On("Delete", input)}
}

func (_c *IRepository_Delete_Call) Run(run func(input inputs.DeleteInput)) *IRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(inputs.DeleteInput))
	})
	return _c
}

func (_c *IRepository_Delete_Call) Return(_a0 error) *IRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IRepository_Delete_Call) RunAndReturn(run func(inputs.DeleteInput) error) *IRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields:
func (_m *IRepository) Get() ([]tables.Users, error) {
	ret := _m.Called()

	var r0 []tables.Users
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]tables.Users, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []tables.Users); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tables.Users)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type IRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *IRepository_Expecter) Get() *IRepository_Get_Call {
	return &IRepository_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *IRepository_Get_Call) Run(run func()) *IRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IRepository_Get_Call) Return(_a0 []tables.Users, _a1 error) *IRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IRepository_Get_Call) RunAndReturn(run func() ([]tables.Users, error)) *IRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Log provides a mock function with given fields: field, values, id, action
func (_m *IRepository) Log(field string, values interface{}, id int, action string) error {
	ret := _m.Called(field, values, id, action)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}, int, string) error); ok {
		r0 = rf(field, values, id, action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IRepository_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type IRepository_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - field string
//   - values interface{}
//   - id int
//   - action string
func (_e *IRepository_Expecter) Log(field interface{}, values interface{}, id interface{}, action interface{}) *IRepository_Log_Call {
	return &IRepository_Log_Call{Call: _e.mock.On("Log", field, values, id, action)}
}

func (_c *IRepository_Log_Call) Run(run func(field string, values interface{}, id int, action string)) *IRepository_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}), args[2].(int), args[3].(string))
	})
	return _c
}

func (_c *IRepository_Log_Call) Return(_a0 error) *IRepository_Log_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IRepository_Log_Call) RunAndReturn(run func(string, interface{}, int, string) error) *IRepository_Log_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: input
func (_m *IRepository) Update(input inputs.UpdateInput) error {
	ret := _m.Called(input)

	var r0 error
	if rf, ok := ret.Get(0).(func(inputs.UpdateInput) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type IRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - input inputs.UpdateInput
func (_e *IRepository_Expecter) Update(input interface{}) *IRepository_Update_Call {
	return &IRepository_Update_Call{Call: _e.mock.On("Update", input)}
}

func (_c *IRepository_Update_Call) Run(run func(input inputs.UpdateInput)) *IRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(inputs.UpdateInput))
	})
	return _c
}

func (_c *IRepository_Update_Call) Return(_a0 error) *IRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IRepository_Update_Call) RunAndReturn(run func(inputs.UpdateInput) error) *IRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewIRepository creates a new instance of IRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRepository {
	mock := &IRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
